# Generated by Django 3.2.25 on 2024-10-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20241017_0119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
